[package]
name = "examples_from_book"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"

reqwest = { version = "0.12.7", features = ["json", "cookies",  "multipart"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0.128"
